# Generated by Django 3.0 on 2020-07-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0002_auto_20200725_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='game/image')),
            ],
        ),
    ]
