# Generated by Django 3.0 on 2020-07-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0003_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameimg', models.ImageField(default='', upload_to='pic/image')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_id', models.IntegerField()),
                ('Username', models.CharField(max_length=50)),
                ('Create_time', models.DateTimeField(auto_now_add=True)),
                ('Game', models.CharField(default='', max_length=50)),
                ('Level', models.IntegerField(default=0)),
                ('Pay_per_round', models.IntegerField(default=0)),
                ('Uuid', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
