# Generated by Django 3.0 on 2020-08-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0005_auto_20200730_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='allview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameimg', models.ImageField(default='', upload_to='allview/image')),
            ],
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
