# Generated by Django 3.0 on 2020-08-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0007_auto_20200805_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='videomodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(default='', upload_to='videofile/video')),
            ],
        ),
    ]
