# Generated by Django 3.0 on 2020-08-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0008_videomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='desc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='file',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
